# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Think Every Day' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod ‘GoogleSignIn’
  pod 'Firebase/Database'
  pod 'FirebaseUI', '~> 0.5'
end
